name: Continuous integration
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make install
      - name: Analyse
        run: make analyse
      - name: Tests
        run: make tests
